[project]
name = "gemini-mcp"
version = "0.1.0"
description = "Gemini MCP Demonstration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
]
